steps:
- name: golang
  args: [go, build, -o, cloudreposlackhook, -ldflags, -w -s, main.go]
  env:
  - CGO_ENABLED=0

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/cloudreposlackhook, '.']
- name: gcr.io/cloud-builders/docker
  args: [tag, gcr.io/$PROJECT_ID/cloudreposlackhook, 'gcr.io/$PROJECT_ID/cloudreposlackhook:$COMMIT_SHA']

images:
- gcr.io/$PROJECT_ID/cloudreposlackhook:latest
- gcr.io/$PROJECT_ID/cloudreposlackhook:$COMMIT_SHA
